name: BlackTureExpansions
version: '${project.version}'
main: ne.fnfal113.fnamplifications.FNAmplifications
api-version: 1.16
authors: [ FN_FAL113 ]
description: hello. Welcome to brain damage zone
website: https://github.com/FN-FAL113
depend: [Slimefun]
softdepend:
  - LiteXpansion
  - SimpleMaterialGenerators
  - Vault
commands:
  fngear:
    description: MDKDSBFIWNURKSBSKDBIWBD send brain help I am dying xxxxxxddddddd
    default: true
    usage: /<command>
  fngear.levelupgears:
    description: Command for levelling up FN Gears
    usage: /<command>
    default: op
